services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ponguser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: PongRank
    volumes:
      - pongrank-db-data:/var/lib/postgresql/data

  ml-webapi:
    build:
      context: ./
      dockerfile: ./src/PongRank.WebApi/Dockerfile
      args:
        - Nuget_CustomFeedUserName=${Nuget_CustomFeedUserName}
        - Nuget_CustomFeedPassword=${Nuget_CustomFeedPassword}
    restart: always
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - DOTNET_ENVIRONMENT=Release
      - DB_PASSWORD=${DB_PASSWORD}
      - ForgeConfiguration__Logging__LokiUrl=https://loki.lan.sangu.be
    volumes:
      - pongrank-ml-models:/ml-models
    depends_on:
      - db

volumes:
  pongrank-db-data:
  pongrank-ml-models:
