version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pongrank-db
    restart: always
    environment:
      POSTGRES_USER: ponguser
      POSTGRES_PASSWORD: ${DB_PASSWORD:-my-secret-pw}
      POSTGRES_DB: PongRank
    ports:
      - "7301:5432"
    networks:
      - pongranknet
    volumes:
      - db-data:/var/lib/postgresql/data

  ml-webapi:
    build:
      context: ./
      dockerfile: ./src/PongRank.WebApi/Dockerfile
      args:
        - Nuget_CustomFeedUserName=${Nuget_CustomFeedUserName}
        - Nuget_CustomFeedPassword=${Nuget_CustomFeedPassword}
    container_name: pongrank-backend
    restart: always
    ports:
      - "7300:5000"
    networks:
      - pongranknet
      - monitoring_monitoring
    environment:
      - DOTNET_ENVIRONMENT=Release
      - DB_PASSWORD=${DB_PASSWORD:-my-secret-pw}
    volumes:
      - /volume1/Projects/PongRank-Logs:/app/logs
      - /volume1/Projects/PongRank-Models:/ml-models
    depends_on:
      - db

volumes:
  db-data:

networks:
  pongranknet:
    driver: bridge
  monitoring_monitoring:
    external: true
