// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PongRank.DataAccess;

#nullable disable

namespace PongRank.DataAccess.Migrations
{
    [DbContext(typeof(TtcDbContext))]
    [Migration("20250428180833_AddPlayerResults")]
    partial class AddPlayerResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PongRank.DataEntities.ClubEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UniqueIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Competition", "Year");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("PongRank.DataEntities.MatchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MatchUniqueId")
                        .HasColumnType("integer");

                    b.Property<string>("WeekName")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("PongRank.DataEntities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Club")
                        .HasColumnType("integer");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ranking")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("UniqueIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Competition", "Year");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PongRank.DataEntities.PlayerResultsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ALosses")
                        .HasColumnType("integer");

                    b.Property<int>("AWins")
                        .HasColumnType("integer");

                    b.Property<int>("B0Losses")
                        .HasColumnType("integer");

                    b.Property<int>("B0Wins")
                        .HasColumnType("integer");

                    b.Property<int>("B2Losses")
                        .HasColumnType("integer");

                    b.Property<int>("B2Wins")
                        .HasColumnType("integer");

                    b.Property<int>("B4Losses")
                        .HasColumnType("integer");

                    b.Property<int>("B4Wins")
                        .HasColumnType("integer");

                    b.Property<int>("B6Losses")
                        .HasColumnType("integer");

                    b.Property<int>("B6Wins")
                        .HasColumnType("integer");

                    b.Property<int>("C0Losses")
                        .HasColumnType("integer");

                    b.Property<int>("C0Wins")
                        .HasColumnType("integer");

                    b.Property<int>("C2Losses")
                        .HasColumnType("integer");

                    b.Property<int>("C2Wins")
                        .HasColumnType("integer");

                    b.Property<int>("C4Losses")
                        .HasColumnType("integer");

                    b.Property<int>("C4Wins")
                        .HasColumnType("integer");

                    b.Property<int>("C6Losses")
                        .HasColumnType("integer");

                    b.Property<int>("C6Wins")
                        .HasColumnType("integer");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<int>("D0Losses")
                        .HasColumnType("integer");

                    b.Property<int>("D0Wins")
                        .HasColumnType("integer");

                    b.Property<int>("D2Losses")
                        .HasColumnType("integer");

                    b.Property<int>("D2Wins")
                        .HasColumnType("integer");

                    b.Property<int>("D4Losses")
                        .HasColumnType("integer");

                    b.Property<int>("D4Wins")
                        .HasColumnType("integer");

                    b.Property<int>("D6Losses")
                        .HasColumnType("integer");

                    b.Property<int>("D6Wins")
                        .HasColumnType("integer");

                    b.Property<int>("E0Losses")
                        .HasColumnType("integer");

                    b.Property<int>("E0Wins")
                        .HasColumnType("integer");

                    b.Property<int>("E2Losses")
                        .HasColumnType("integer");

                    b.Property<int>("E2Wins")
                        .HasColumnType("integer");

                    b.Property<int>("E4Losses")
                        .HasColumnType("integer");

                    b.Property<int>("E4Wins")
                        .HasColumnType("integer");

                    b.Property<int>("E6Losses")
                        .HasColumnType("integer");

                    b.Property<int>("E6Wins")
                        .HasColumnType("integer");

                    b.Property<int>("FLosses")
                        .HasColumnType("integer");

                    b.Property<int>("FWins")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NGLosses")
                        .HasColumnType("integer");

                    b.Property<int>("NGWins")
                        .HasColumnType("integer");

                    b.Property<string>("NextRanking")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int?>("NextRankingValue")
                        .HasColumnType("integer");

                    b.Property<string>("Ranking")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("RankingValue")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PlayerResults");
                });

            modelBuilder.Entity("PongRank.DataEntities.MatchEntity", b =>
                {
                    b.OwnsOne("PongRank.DataEntities.MatchEntityPlayer", "Away", b1 =>
                        {
                            b1.Property<int>("MatchEntityId")
                                .HasColumnType("integer");

                            b1.Property<int>("PlayerUniqueIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("SetCount")
                                .HasColumnType("integer");

                            b1.HasKey("MatchEntityId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchEntityId");
                        });

                    b.OwnsOne("PongRank.DataEntities.MatchEntityPlayer", "Home", b1 =>
                        {
                            b1.Property<int>("MatchEntityId")
                                .HasColumnType("integer");

                            b1.Property<int>("PlayerUniqueIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("SetCount")
                                .HasColumnType("integer");

                            b1.HasKey("MatchEntityId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchEntityId");
                        });

                    b.Navigation("Away")
                        .IsRequired();

                    b.Navigation("Home")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
